### ISSUE TITLE
Compatibility with .zip and .7z

### ISSUE THREAD

**Issue by MerchiBCP** [jrathlev/DosPanel#2]
**English**

Hello,

To begin, I wanted to thank you for your application, which is very practical.

However I have a request, could you include compatibility with .zip and .7z files, because the majority of Romsets look like this, moreover leaving them Isos or Roms compressed saves space.

Hoping this is technically possible.

And if it is not possible it does not matter and thank you again.

**Français**

Bonjour,

Pour commence je tenais à vous remercie pour votre application qui est très pratique. 

Cependant j’ai une requête, pourriez-vous inclure la compatibilité avec les fichiers .zip et .7z, car la majorité des Romsets se présentent ainsi, de plus de les laisser les Isos ou les Roms compressés permet de gagner de l’espace. 

En espérant que cela soit possible techniquement.

Et si ce n’est pas possible ce n’est pas grave et merci encore.

**Comment by jrathlev** [comment]
This would require an extension in dosbox. Please send your request to the dosbox developers.
